---
version: "3.6"
services:
  es_server:
    image: es_server
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      MYSQL_HOST: es_database
      MYSQL_USER: engelsystem
      MYSQL_PASSWORD: engelsystem
      MYSQL_DATABASE: engelsystem
      ENABLE_USER_NAME: 1
    ports:
      - "5080:80"
    env_file: deployment.env
    networks:
      - database
      - internet
    depends_on:
      - es_database
  es_database:
    image: mariadb
    environment:
      MYSQL_DATABASE: engelsystem
      MYSQL_USER: engelsystem
      MYSQL_PASSWORD: engelsystem
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_INITDB_SKIP_TZINFO: "yes"
    volumes:
      - db:/var/lib/mysql
    networks:
      - database
  db_admin:
    image: phpmyadmin
    environment:
      PMA_HOST: es_database
    networks:
      - database
      - internet
    ports:
      - "8080:80"

volumes:
  db: {}

networks:
  database:
    internal: true
  internet:
